### ISSUE TITLE
demande

### ISSUE THREAD

**Issue by Pano29Officiel** [ProjectMakerGithub/ProjectMakerGithub.github.io#1]
@all-contributors please add @Pano29Officiel for administrateur, dévellopeur et gérant de la documentation.

**Comment by ProjectMakerGithub** [comment]
https://github.com/all-contributors please add @Pano29Officiel for administrateur, dévellopeur et gérant de la documentation.

**Comment by Pano29Officiel** [comment]
@all-contributors please add @<username> for <contributions>

**Comment by Pano29Officiel** [comment]
@all-contributors please add @Pano29Officiel for administrateur, développeur et gérant de la documentation.
